module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        "xsm": '200px',
        sm: '480px',
        md: '768px',
        lg: '976px',
        xl: '1440px',
      },
      colors: {
        'BgScreen': '#EDEFF2',
        'gradientDarkBlue': '#4252EC',
        'gradientLightBlue': '#6F7CFB',
        'HeadingColor': '#3A50E4',
        'themeColorBg': '#f7f6f6',
        'MenuBarBg': '#23262B',
        'MainBg': '#F2F5FF',
        'MainHeading': '#3A4059',
        'SubHeading': '#6D6D6D',
        'GrayScale': 'rgba(0, 0, 0, 0.06)',
        'BorderColor': '#D5D5D5',
        'Overlay': 'rgba(0, 0, 0, 0.32)',
        'Placeholder': '#767676',
        'SelectHover': '#F3F3F3',
        'CancelBtn': '#808286',
        'TimelineGray': '#D0D2E2',
        'TimelineText': '#9395A8',
        'ToolTipBg': '#000527',
        'payCard': "#3A50E4",
        'payCardBg':"#ECF3FF",
        'horizontalLine':"#DEDEDE",
        'SubTableHead':"#DBE8FF",
      },
      fontSize: {
        sm: '0.6rem',
        md:"0.8rem",
        base: '1rem',
        xl: '1.25rem',
        '2xl': '1.563rem',
        '3xl': '1.953rem',
        '4xl': '2.441rem',
        '5xl': '3.052rem',
      },
      fontFamily: {
        'OB': ['Orbitron-Black'],
        'Ob': ['Orbitron-Bold'],
        'Oeb': ['Orbitron-ExtraBold'],
        'Om':['Orbitron-Medium'],
        'Or':['Orbitron-Regular'],
        'Osb': ['Orbitron-SemiBold'],
        'Ovf':['Orbitron-VariableFont_wght'],
        'PB': ['Poppins-Black'],
        'PBi': ['Poppins-BlackItalic'],
        'Pb': ['Poppins-Bold'],
        'Pbi': ['Poppins-BoldItalic'],
        'Peb': ['Poppins-ExtraBold'],
        'Pebi': ['Poppins-ExtraBoldItalic'],
        'Pel': ['Poppins-ExtraLight'],
        'Peli': ['Poppins-ExtraLightItalic'],
        'Pi': ['Poppins-Italic'],
        'Pl': ['Poppins-Light'],
        'Pli': ['Poppins-LightItalic'],
        'Pm': ['Poppins-Medium'],
        'Pmi': ['Poppins-MediumItalic'],
        'Pr':['Poppins-Regular'],
        'Psb': ['Poppins-SemiBold'],
        'Psbi': ['Poppins-SemiBoldItalic'],
        'Pt': ['Poppins-Thin'],
        'Pti': ['Poppins-ThinItalic'],
      },
      margin: {
        '50px': '50px',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        DEFAULT: '4px',
        'md': '0.375rem',
        'lg': '0.5rem',
        'full': '9999px',
        'large': '12px',
      }
      // plugins: [
      //   require('@tailwindcss/forms'),
      // ],
    },
  },
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
  ],
}